cluster-worker:
  src: ssh://git@git.plgrid.pl:7999/vfs/cluster-worker.git
  dst: ssh://git@github.com/onedata/cluster-worker.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
    - '*'

ctool:
  src: ssh://git@git.plgrid.pl:7999/vfs/ctool.git
  dst: ssh://git@github.com/onedata/ctool.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
    - '*'

cluster-manager:       
  src: ssh://git@git.plgrid.pl:7999/vfs/cluster-manager.git
  dst: ssh://git@github.com/onedata/cluster-manager.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
    - '*'

op-worker:
  src: ssh://git@git.plgrid.pl:7999/vfs/op-worker.git
  dst: ssh://git@github.com/onedata/op-worker.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
    - '*'

clproto:
  src: ssh://git@git.plgrid.pl:7999/vfs/clproto.git
  dst: ssh://git@github.com/onedata/clproto.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
    - '*'

web-client:
  src: ssh://git@git.plgrid.pl:7999/vfs/web-client.git
  dst: ssh://git@github.com/onedata/web-client.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
    - '*'

onepanel:
  src: ssh://git@git.plgrid.pl:7999/vfs/onepanel.git
  dst: ssh://git@github.com/onedata/onepanel.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
    - '*'


helpers:
  src: ssh://git@git.plgrid.pl:7999/vfs/helpers.git
  dst: ssh://git@github.com/onedata/helpers.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
    - '*'

oneclient:
  src: ssh://git@git.plgrid.pl:7999/vfs/oneclient.git
  dst: ssh://git@github.com/onedata/oneclient.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
    - '*'

luma:
  src: ssh://git@git.plgrid.pl:7999/vfs/luma.git 
  dst: ssh://git@github.com/onedata/luma.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
    - '*'

onezone:
  src: ssh://git@git.plgrid.pl:7999/vfs/luma.git 
  dst: git@github.com:onedata/onezone.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
    - '*'

onezone:
  src: ssh://git@git.plgrid.pl:7999/vfs/onezone.git 
  dst: git@github.com:onedata/onezone.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
    - '*'

onedata:
  src: ssh://git@git.plgrid.pl:7999/vfs/onedata.git 
  dst: git@github.com:onedata/onedata.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
    - '*'

oz-worker:
  src: ssh://git@git.plgrid.pl:7999/vfs/oz-worker.git
  dst: git@github.com:onedata/oz-worker.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
    - '*'

appmock:
  src: ssh://git@git.plgrid.pl:7999/vfs/appmock.git
  dst: ssh://git@github.com/onedata/appmock.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
    - '*'

bamboos:
  src: ssh://git@git.plgrid.pl:7999/vfs/bamboos.git
  dst: ssh://git@github.com/onedata/bamboos.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
   - '*'

erlang-tls:
  src: ssh://git@git.plgrid.pl:7999/vfs/erlang-tls.git
  dst: ssh://git@github.com/onedata/erlang-tls.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - develop
   - release/*
  tags:
    - '*'

docker-ceph-base:
  src: ssh://git@git.plgrid.pl:7999/vfs/docker-ceph-base.git
  dst: ssh://git@github.com/onedata/docker-ceph-base.git
  did: /onedata_github
  sid: /onedata_github
  branches:
   - master
   - release/*
  tags:
    - '*'
