---
# Official Onedata Github
cluster-worker:
  src: ssh://git@git.onedata.org:7999/vfs/cluster-worker.git
  dst: ssh://git@github.com/onedata/cluster-worker.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

ctool:
  src: ssh://git@git.onedata.org:7999/vfs/ctool.git
  dst: ssh://git@github.com/onedata/ctool.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

cluster-manager:
  src: ssh://git@git.onedata.org:7999/vfs/cluster-manager.git
  dst: ssh://git@github.com/onedata/cluster-manager.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

op-worker:
  src: ssh://git@git.onedata.org:7999/vfs/op-worker.git
  dst: ssh://git@github.com/onedata/op-worker.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

clproto:
  src: ssh://git@git.onedata.org:7999/vfs/clproto.git
  dst: ssh://git@github.com/onedata/clproto.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

web-client:
  src: ssh://git@git.onedata.org:7999/vfs/web-client.git
  dst: ssh://git@github.com/onedata/web-client.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

onepanel:
  src: ssh://git@git.onedata.org:7999/vfs/onepanel.git
  dst: ssh://git@github.com/onedata/onepanel.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

helpers:
  src: ssh://git@git.onedata.org:7999/vfs/helpers.git
  dst: ssh://git@github.com/onedata/helpers.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

oneclient:
  src: ssh://git@git.onedata.org:7999/vfs/oneclient.git
  dst: ssh://git@github.com/onedata/oneclient.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

luma:
  src: ssh://git@git.onedata.org:7999/vfs/luma.git
  dst: ssh://git@github.com/onedata/luma.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

onezone:
  src: ssh://git@git.onedata.org:7999/vfs/onezone.git
  dst: git@github.com:onedata/onezone.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

onedata:
  src: ssh://git@git.onedata.org:7999/vfs/onedata.git
  dst: git@github.com:onedata/onedata.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

oz-worker:
  src: ssh://git@git.onedata.org:7999/vfs/oz-worker.git
  dst: git@github.com:onedata/oz-worker.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

appmock:
  src: ssh://git@git.onedata.org:7999/vfs/appmock.git
  dst: ssh://git@github.com/onedata/appmock.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

bamboos:
  src: ssh://git@git.onedata.org:7999/vfs/bamboos.git
  dst: ssh://git@github.com/onedata/bamboos.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

erlang-tls:
  src: ssh://git@git.onedata.org:7999/vfs/erlang-tls.git
  dst: ssh://git@github.com/onedata/erlang-tls.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

docker-ceph-base:
  src: ssh://git@git.onedata.org:7999/vfs/docker-ceph-base.git
  dst: ssh://git@github.com/onedata/docker-ceph-base.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - release/*
  tags:
    - '*'

cluster-example:
  src: ssh://git@git.onedata.org:7999/vfs/cluster-example.git
  dst: ssh://git@github.com/onedata/cluster-example.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - release/*
  tags:
    - '*'

onepanel-swagger:
  src: ssh://git@git.onedata.org:7999/vfs/onepanel-swagger.git
  dst: ssh://git@github.com/onedata/onepanel-swagger.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - release/*
  tags:
    - '*'

oneprovider-swagger:
  src: ssh://git@git.onedata.org:7999/vfs/oneprovider-swagger.git
  dst: ssh://git@github.com/onedata/oneprovider-swagger.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - release/*
  tags:
    - '*'

onezone-swagger:
  src: ssh://git@git.onedata.org:7999/vfs/onezone-swagger.git
  dst: ssh://git@github.com/onedata/onezone-swagger.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - release/*
  tags:
    - '*'

gui:
  src: ssh://git@git.onedata.org:7999/vfs/gui.git
  dst: ssh://git@github.com/onedata/gui.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

onedata-documentation:
  src: ssh://git@git.onedata.org:7999/vfs/onedata-documentation.git
  dst: ssh://git@github.com/onedata/onedata-documentation.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - '*'
  tags:
    - '*'

github-publish:
  src: ssh://git@git.onedata.org:7999/vfs/github-publish.git
  dst: ssh://git@github.com/onedata/github-publish.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - '*'
  tags:
    - '*'

swagger-codegen-cowboy:
  src: ssh://git@git.onedata.org:7999/vfs/swagger-codegen-cowboy.git
  dst: ssh://git@github.com/onedata/swagger-codegen-cowboy.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - '*'
  tags:
    - '*'

homebrew-onedata:
  src: ssh://git@git.onedata.org:7999/vfs/homebrew-onedata.git
  dst: ssh://git@github.com/onedata/homebrew-onedata.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
  tags:
    - '*'

ember-cli-onedata-common:
  src: ssh://git@git.onedata.org:7999/vfs/ember-cli-onedata-common.git
  dst: ssh://git@github.com/onedata/ember-cli-onedata-common.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

oz-gui-default:
  src: ssh://git@git.onedata.org:7999/vfs/oz-gui-default.git
  dst: ssh://git@github.com/onedata/oz-gui-default.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

op-gui-default:
  src: ssh://git@git.onedata.org:7999/vfs/op-gui-default.git
  dst: ssh://git@github.com/onedata/op-gui-default.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

oz-gui-homepage:
  src: ssh://git@git.onedata.org:7999/vfs/oz-gui-homepage.git
  dst: ssh://git@github.com/onedata/oz-gui-homepage.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

docker-volume-onedata:
  src: ssh://git@git.onedata.org:7999/vfs/docker-volume-onedata.git
  dst: ssh://git@github.com/onedata/docker-volume-onedata.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - '*'
  tags:
    - '*'

onepanel-javascript-client:
  src: ssh://git@git.onedata.org:7999/vfs/onepanel-javascript-client.git
  dst: ssh://git@github.com/onedata/onepanel-javascript-client.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - '*'
  tags:
    - '*'

docker-openvpn-kube-for-mac:
  src: ssh://git@git.onedata.org:7999/vfs/docker-openvpn-kube-for-mac.git
  dst: ssh://git@github.com/onedata/docker-openvpn-kube-for-mac.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - '*'
  tags:
    - '*'

cberl:
  src: ssh://git@git.onedata.org:7999/vfs/cberl.git
  dst: ssh://git@github.com/onedata/cberl.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
  tags:
    - '*'

rest-cli-docker:
  src: ssh://git@git.onedata.org:7999/vfs/rest-cli-docker.git
  dst: ssh://git@github.com/onedata/rest-cli-docker.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
  tags:
    - '*'
    
onezone-gui:
  src: ssh://git@git.onedata.org:7999/vfs/onezone-gui.git
  dst: ssh://git@github.com/onedata/onezone-gui.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
  tags:
    - '*'
    
ioreplay:
  src: ssh://git@git.onedata.org:7999/vfs/ioreplay.git
  dst: ssh://git@github.com/onedata/ioreplay.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
  tags:
    - '*'

onedata-gui-common:
  src: ssh://git@git.onedata.org:7999/vfs/onedata-gui-common.git
  dst: ssh://git@github.com/onedata/onedata-gui-common.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
  tags:
    - '*'
  
hps-b2handle:
  src: ssh://git@git.onedata.org:7999/vfs/hps-b2handle.git
  dst: ssh://git@github.com/onedata/hps-b2handle.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
  tags:
    - '*'

fs-onedatafs:
  src: ssh://git@git.onedata.org:7999/vfs/fs-onedatafs.git
  dst: ssh://git@github.com/onedata/fs-onedatafs.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*1
  tags:
    - '*'

onedatafs-jupyter:
  src: ssh://git@git.onedata.org:7999/vfs/onedatafs-jupyter.git
  dst: ssh://git@github.com/onedata/onedatafs-jupyter.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

# Onedata Indigo Github

oneclient-idc:
  src: ssh://git@git.onedata.org:7999/vfs/oneclient.git
  dst: ssh://git@github.com/indigo-dc/oneclient.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

luma-idc:
  src: ssh://git@git.onedata.org:7999/vfs/luma.git
  dst: ssh://git@github.com/indigo-dc/luma.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

onezone-idc:
  src: ssh://git@git.onedata.org:7999/vfs/onezone.git
  dst: git@github.com:indigo-dc/onezone.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'

onedata-idc:
  src: ssh://git@git.onedata.org:7999/vfs/onedata.git
  dst: git@github.com:indigo-dc/onedata.git
  did: /onedata_github
  sid: /onedata_github
  branches:
    - master
    - develop
    - release/*
  tags:
    - '*'
